{% set name = "napari-tomoslice" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e16c6fdc0eaa8efc20b81ff28f7d200167f6f9f69b692a965061aac7143a23af

build:
  entry_points:
    - napari-tomoslice = napari_tomoslice.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - mrcfile
    - napari ==0.4.12
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - typer

test:
  imports:
    - napari_tomoslice
  commands:
    - pip list
    - pip check
    - napari-tomoslice --help
  requires:
    - pip

about:
  home: https://github.com/alisterburt/napari-tomoslice
  summary: A napari plugin for interacting with electron cryotomograms
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alisterburt
    - goanpeca
    - jaimergp
